seed_everything: 1
trainer:
  accelerator: gpu
  gpus: 1
  gradient_clip_val: 0.5
  max_epochs: 100
  accumulate_grad_batches: 32
  log_every_n_steps: 5
  check_val_every_n_epoch: 10
  num_sanity_val_steps: 0
  default_root_dir: ./ckpt
  callbacks:
      - class_path: pytorch_lightning.callbacks.LearningRateMonitor
        init_args:
          logging_interval: step

model:
  lr: 2e-4
  warmup_steps: 800
  model_name: gpt2
  num_beams: 5
  topk: 10
data:
  dataset: entailmentbank
  batch_size: 1
  num_workers: 2
  max_input_len: 256
  max_output_len: 256
  path_train: /home/ysuay/codes/LLM+Reason/codes/LLMProofs/data_prompt/entailment_verifier_task2_samples.txt
  path_val: /home/ysuay/codes/LLM+Reason/codes/LLMProofs/data_prompt/entailment_verifier_task2_samples.txt
