seed_everything: 1
trainer:
  accelerator: gpu
  gpus: 1
  gradient_clip_val: 0.5
  max_epochs: 100
  accumulate_grad_batches: 1
  log_every_n_steps: 5
  check_val_every_n_epoch: 10
  num_sanity_val_steps: 0
  default_root_dir: ./ckpt-flan-t5-large
  callbacks:
      - class_path: pytorch_lightning.callbacks.LearningRateMonitor
        init_args:
          logging_interval: step
      - class_path: pytorch_lightning.callbacks.ModelCheckpoint
        init_args:
          every_n_epochs: 10
          save_on_train_epoch_end: true
          save_weights_only: true
model:
  lr: 1e-4 #5e-5
  warmup_steps: 800
  model_name: google/flan-t5-large
  num_beams: 5
  topk: 10
data:
  dataset: entailmentbank
  batch_size: 32
  num_workers: 4
  max_input_len: 256
  max_output_len: 256
  path_train: ../data_sample/reasoner_task1_samples.txt
  path_val: ../data_sample/reasoner_task1_samples.txt
