seed_everything: 1
trainer:
  gpus: 1
  gradient_clip_val: 0.5
  max_epochs: 20
  accumulate_grad_batches: 16
  log_every_n_steps: 5
  check_val_every_n_epoch: 2
  default_root_dir: ./ckpt_entailmentbank_task1
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args: 
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        every_n_epochs: 2
        save_on_train_epoch_end: true

model:
  stepwise: true
  max_num_steps: 20
  lr: 0.0001
  warmup_steps: 0
  model_name: google/flan-t5-large
  model_path: ../stepwise/ckpt_entailmentbank_task1/lightning_logs/version0/epoch\=499-step\=10500.ckpt
  num_beams: 10
  topk: 10

data:
  dataset: entailmentbank
  sample_goal: hypothesis # hypothesis | intermediates
  subtree_proved_prob: 0.5
  subtree_proved_all_or_none: true
  batch_size: 4
  num_workers: 4
  max_input_len: 1024
  max_output_len: 64
  hard_type: vanilla
  hard_prob: 0.0
  path_train: ../data/entailment_trees_emnlp2021_data_v3/dataset/task_1/train.jsonl
  path_train_contrast: none
  path_val: ../data/entailment_trees_emnlp2021_data_v3/dataset/task_1/dev.jsonl
  path_test: ../data/entailment_trees_emnlp2021_data_v3/dataset/task_1/test.jsonl
