seed_everything: 1
trainer:
  accelerator: gpu
  gpus: 1
  gradient_clip_val: 0.5
  max_epochs: 700
  accumulate_grad_batches: 32
  log_every_n_steps: 5
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 10
  default_root_dir: /home/ysuay/codes/LLM+Reason/codes/LLMProofs/train_slic/prover/ckpt_entailmentbank_task2
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args: 
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        every_n_epochs: 2
        save_on_train_epoch_end: true

model:
  stepwise: true
  max_num_steps: 20
  lr: 1e-5
  warmup_steps: 1000
  model_name: t5-large
  num_beams: 10
  topk: 10
  verifier_ckpt: null
  verifier_weight: 0.0
  proof_search: false
data:
  dataset: entailmentbank
  batch_size: 1
  num_workers: 1
  max_input_len: 1024
  max_output_len: 64
  path_train: /home/ysuay/codes/LLM+Reason/codes/LLMProofs/offline/eval_entailmentbank_task2/lightning_logs/version_4/results_train.json 
  path_val: /home/ysuay/codes/LLM+Reason/codes/NLProofS/data/entailment_trees_emnlp2021_data_v3/dataset/task_2/dev.jsonl
  path_test: /home/ysuay/codes/LLM+Reason/codes/NLProofS/data/entailment_trees_emnlp2021_data_v3/dataset/task_2/test.jsonl
